name: Build JafarSchool APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List ZIP
        run: ls -la *.zip

      - name: Extract ZIP
        run: unzip -q *.zip -d extracted

      - name: Find Project
        run: find extracted -name settings.gradle -print

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
